export const CLOVE_CLASSES = {
    chart: 'clove-chart',
    chartWrapper: 'clove-chart-wrapper',
    plot: 'clove-plot',
    plotBackground: 'clove-plot-background',
    axes: 'clove-axes',
    xAxis: 'clove-x-axis',
    yAxis: 'clove-y-axis',
    axisLabel: 'clove-axis-label',
    grid: 'clove-grid',
    legend: 'clove-legend',
    legendTitle: 'clove-legend-title',
    legendItem: 'clove-legend-item',
    legendSymbol: 'clove-legend-symbol',
    tooltip: 'clove-tooltip',
    tooltipRow: 'clove-tooltip-row',
    tooltipLabel: 'clove-tooltip-label',
    tooltipValue: 'clove-tooltip-value',
    header: 'clove-header',
    footer: 'clove-footer',
    captions: 'clove-captions',
} as const;
